<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ru_RU">
  <context>
    <name>Settings</name>
    <message>
      <source>Save</source>
      <translation>Сохранить</translation>
    </message>
    <message>
      <source>Cancel</source>
      <translation>Отмена</translation>
    </message>
    <message>
      <source>Back</source>
      <translation>Назад</translation>
    </message>
    <message>
      <source>Theme</source>
      <translation>Тема</translation>
    </message>
    <message>
      <source>Language</source>
      <translation>Язык</translation>
    </message>
    <message>
      <source>Notifications</source>
      <translation>Уведомления</translation>
    </message>
    <message>
      <source>Light</source>
      <translation>Светлая</translation>
    </message>
    <message>
      <source>Dark</source>
      <translation>Тёмная</translation>
    </message>
    <message>
      <source>Auto</source>
      <translation>Автоматически</translation>
    </message>
    <message>
      <source>English</source>
      <translation>Английский</translation>
    </message>
    <message>
      <source>Armenian</source>
      <translation>Армянский</translation>
    </message>
    <message>
      <source>Russian</source>
      <translation>Русский</translation>
    </message>
    <message>
      <source>Enabled</source>
      <translation>Включено</translation>
    </message>
    <message>
      <source>Disabled</source>
      <translation>Отключено</translation>
    </message>
    <name>MyProfile</name>
    <message>
        <source>Settings</source>
        <translation>Настройки</translation>
    </message>
    <message>
        <source>Log Out</source>
        <translation>Выйти</translation>
    </message>
    <message>
        <source>Edit</source>
        <translation>Редактировать</translation>
    </message>
    <message>
        <source>Change</source>
        <translation>Изменить</translation>
    </message>
    <message>
        <source>Back</source>
        <translation>Назад</translation>
    </message>
    <name>OtherProfile</name>
    <message>
        <source>Back</source>
        <translation>Назад</translation>
    </message>
  </context>
</TS>
