<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="hy_AM">
    <context>
        <name>Settings</name>
        <message>
            <source>Save</source>
            <translation>Պահպանել</translation>
        </message>
        <message>
            <source>Cancel</source>
            <translation>Չեղարկել</translation>
        </message>
        <message>
            <source>Back</source>
            <translation>Հետ</translation>
        </message>
        <message>
            <source>Theme</source>
            <translation>Թեմա</translation>
        </message>
        <message>
            <source>Language</source>
            <translation>Լեզու</translation>
        </message>
        <message>
            <source>Notifications</source>
            <translation>Ծանուցումներ</translation>
        </message>
        <message>
            <source>Light</source>
            <translation>Լույս</translation>
        </message>
        <message>
            <source>Dark</source>
            <translation>Մութ</translation>
        </message>
        <message>
            <source>Auto</source>
            <translation>Ավտո</translation>
        </message>
        <message>
            <source>English</source>
            <translation>Անգլերեն</translation>
        </message>
        <message>
            <source>Armenian</source>
            <translation>Հայերեն</translation>
        </message>
        <message>
            <source>Russian</source>
            <translation>Ռուսերեն</translation>
        </message>
        <message>
            <source>Enabled</source>
            <translation>Միացված</translation>
        </message>
        <message>
            <source>Disabled</source>
            <translation>Անջատված</translation>
        </message>
        <name>MyProfile</name>
        <message>
            <source>Settings</source>
            <translation>Կարգավորումներ</translation>
        </message>
        <message>
            <source>Log Out</source>
            <translation>Դուրս գալ</translation>
        </message>
        <message>
            <source>Edit</source>
            <translation>Խմբագրել</translation>
        </message>
        <message>
            <source>Change</source>
            <translation>Փոխել</translation>
        </message>
        <message>
            <source>Back</source>
            <translation>Հետ</translation>
        </message>
        <name>OtherProfile</name>
        <message>
            <source>Back</source>
            <translation>Հետ</translation>
        </message>
    </context>
</TS>
